# Generated by cucumber-sinatra. (2015-06-30 17:16:32 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/todo_app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = TodoApp

class TodoAppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  TodoAppWorld.new
end
