source 'https://rubygems.org'

gem 'sinatra'
gem 'rack-flash3'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'bcrypt'
gem 'json'
gem 'activesupport', '~> 4.2.2'

group :development, :test do

  gem 'capybara'
  gem 'cucumber'
  gem 'cucumber-sinatra'
  gem 'launchy'
  gem 'rspec'
  gem 'shotgun'
end

